version: '3.4'

services:
  eventservice.api:
    image: ${DOCKER_REGISTRY-}eventserviceapi
    build:
      context: .
      dockerfile: EventService.API/Dockerfile

  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: IdentityServer.Api/Dockerfile

  inventoryservice.api:
    image: ${DOCKER_REGISTRY-}inventoryserviceapi
    build:
      context: .
      dockerfile: InventoryService.Api/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management

volumes:
  eventdb:
  identitydb:
