version: '3.4'

services:
  eventservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7360
      - ASPNETCORE_HTTPS_PORTS=7361
      - ConnectionStrings__database=Server=postgres;Port=5432;Database=eventdb;User Id=postgres;Password=postgres;Include Error Detail=true
      - JWT__Issuer=https://localhost:7371/
      - JWT__Audience=https://localhost:7361/
      - JWT__SigningKey=asjhgreqfetjyukmjhfngdbfvsdarwhetryutiyoiuytrteyrtuioadsfghjhkjghgfdpqerwtegc
      - AzureStorage__Uri=https://vou.blob.core.windows.net
      - MessageBroker__Host=amqp://rabbitmq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    ports:
      - "7360:7360"
      - "7361:7361"
    depends_on:
      - eventdb
      - rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  eventdb:
     container_name: postgres
     image: postgres
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=eventdb
     ports:
       - "5432:5432"
     volumes:
       - eventdb:/var/lib/postgresql/data/

  identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7370
      - ASPNETCORE_HTTPS_PORTS=7371
      - ConnectionStrings__DefaultConnection=Server=identitydb;Database=IdentityDb;User Id=sa;Password=KhiemBi!317;Encrypt=False;TrustServerCertificate=True
      - JWT__Issuer=https://localhost:7371/
      - JWT__Audience=https://localhost:7361/
      - JWT__SigningKey=asjhgreqfetjyukmjhfngdbfvsdarwhetryutiyoiuytrteyrtuioadsfghjhkjghgfdpqerwtegc
    ports:
      - "7370:7370"
      - "7371:7371"
    depends_on:
      - identitydb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  identitydb:
    container_name: identitydb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=KhiemBi!317
    ports:
      - "1433:1433"
    restart: always

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest